// custom-elements/demos/react/src/App.js
import React, { Component } from 'react';

class App extends Component {
  logVueEvent() {
    console.log("copy event from Vue");
  }

  logDojo2Event() {
    console.log("copy event from Dojo 2");
  }
  componentDidMount() {
    // When the component is mounted, add your DOM listener to the "nv" elem.
    // (The "nv" elem is assigned in the render function.)
    this.vue.addEventListener("copy", this.logVueEvent);
    this.dojo2.addEventListener("copy", this.logDojo2Event);
  }

  componentWillUnmount() {
    // Make sure to remove the DOM listener when the component is unmounted.
    this.vue.removeEventListener("copy", this.logVueEvent);
    this.dojo2.removeEventListener("copy", this.logDojo2Event);
  }

  render() {
    return (
      <div className="grid-container">
        <div className="column-24 leader-1">
          <vanilla-card>
            <h4 className="trailer-0" slot="header">Header</h4>
            <h1 className="leader-1 trailer-half">Vue Copyable Text</h1>
            <vue-copyable-text ref={elem => this.vue = elem} label="Copy Me!" text="Copied!"></vue-copyable-text>

            <h1 className="leader-1 trailer-half">Dojo 2 Copyable Text</h1>
            <dojo-2-copyable-text ref={elem => this.dojo2 = elem} onCopy={this.logDojo2Event} label="Copy Me!" text="Copied!"></dojo-2-copyable-text>
            <p className="font-size--2 text-dark-gray trailer-0" slot="footer">Misc Info</p>
          </vanilla-card>
        </div>
      </div>
    );
  }
}

export default App;

// custom-elements/demos/vue/src/App.vue
<template>
  <div class="grid-container">
    <div class="column-24">
      <VueCopyableText v-on:copy="logCopy" class="leader-1 trailer-1" label="Copy Me!" text="Copied!"></VueCopyableText>

      <VueCard class="leader-1">
        <h4 class="trailer-0" slot="header">Header</h4>
        <p>This is the body of the card&hellip;</p>
        <p class="font-size--2 text-dark-gray trailer-0" slot="footer">Misc Info</p>
      </VueCard>
    </div>
  </div>
</template>

<script>
import VueCard from "./components/Card.vue";
import VueCopyableText from "./components/CopyableText.vue";

export default {
  name: "app",
  components: {
    VueCard,
    VueCopyableText
  },
  methods: {
    logCopy: function() {
      console.log("copy event");
    }
  }
};
</script>
